name: "Action Link Checker"
description: "Checks for broken links in a file and reports them."
author: "yankeexe"
inputs:
  file_path:
    description: "Path to the file to parse"
    required: true
  concurrent_workers:
    description: "Number of concurrent workers to use for checking links"
    required: false
    default: '30'
  timeout_seconds:
    description: "Timeout in seconds for each link check"
    required: false
    default: '5'
runs:
  using: "docker"
  image: "docker://ghcr.io/yankeexe/action-link-checker:main"
